[workspace]
resolver = "2"
members = ["crates/adbm-core", "crates/adbm-ffi", "apps/linux"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/oss96/ADBManager"
rust-version = "1.82"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
